SAWTOOTH_STATE_NOT_FOUND_CODE = 75
SAWTOOTH_STATE_NOT_FOUND = "State Not Found"
HTTP_STATUS_404 = 404
PEER_VERIFICATION_REQUEST = "peer_verify_request"  # used to set Action field in PeerVerificationTransaction
PEER_VERIFICATION_RESPONSE = "peer_verify_response"  # used to set Action field in PeerVerificationTransaction
UPDATE_STATE_ACK = "update_acknowledgement"
SHARE_ID_REQUEST = "ID_request"
SHARE_ID_RESPONSE = "ID_response"
PEER_VERIFICATION_REWARD = 10
UNINITIATED_ID_TRUST_SCORE = 0
PRIMARY_CERTIFIED_TRUST_SCORE = 1  # added Apr 10, 2020
CONFIRMED_ID_TRUST_SCORE = 10
MAX_CLIENT_TRUST_SCORE = 20
TRANSACTION_TIMED_OUT_ERROR = "Transaction Timed Out"
PEER_VERIFICATION_WAIT_DAY = 7
TRANSACTION_TIMEOUT_WAIT_SEC = 10  # SEC
# MIN_AVG_TRUST_SCORE = 10   # TODO commented as not being used
# MAX_AVG_TRUST_SCORE = 20  # TODO replace it's usage with CONFIRMED_ID_TRUST_SCORE
MIN_PEER_COUNT = 3  # old value: 2
MAX_PEER_COUNT = 5  # old value: 4
PEER_FILE_NAME = 'peer'
CERTIFIER_CONFIG_FILE = 'certifier_config.txt'
PEER_VERIFY_TIMER = 2 * 60  # in seconds 72 * 3600
MAX_ATTRIBUTE_STRENGTH = 100
TYPE_CREDIBILITY_INC = "CREDIBILITY_INC"  # used to set Type field in PeerVerificationTransaction
TYPE_ID_CREATE = "ID_CREATION"  # used to set Type field in PeerVerificationTransaction
CODE_FILE_NAME = "code_file"
