SAWTOOTH_STATE_NOT_FOUND_CODE = 75
SAWTOOTH_STATE_NOT_FOUND = "State Not Found"
HTTP_STATUS_404 = 404
TRANSACTION_TIMED_OUT_ERROR = "Transaction Timed Out"
TRANSACTION_TIMEOUT_WAIT_SEC = 10  # SEC
CODE_FILE_NAME = "code_file"
