# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/peer_verification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import digital_id_pb2 as protobuf_dot_digital__id__pb2
try:
  protobuf_dot_id__attribute__pb2 = protobuf_dot_digital__id__pb2.protobuf_dot_id__attribute__pb2
except AttributeError:
  protobuf_dot_id__attribute__pb2 = protobuf_dot_digital__id__pb2.protobuf.id_attribute_pb2
from protobuf import client_pb2 as protobuf_dot_client__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/peer_verification.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n protobuf/peer_verification.proto\x1a\x19protobuf/digital_id.proto\x1a\x15protobuf/client.proto\"\x86\x01\n\x17PeerVerificationRequest\x12\x12\n\ndigital_id\x18\x01 \x01(\x0c\x12\x17\n\x0fowner_signature\x18\x02 \x01(\t\x12\x0e\n\x06remark\x18\x03 \x01(\t\x12\x14\n\x0cpeer_address\x18\x04 \x01(\t\x12\x18\n\x10\x63reate_timestamp\x18\x05 \x01(\t\"l\n\x18PeerVerificationResponse\x12\x12\n\ndigital_id\x18\x01 \x01(\x0c\x12\x16\n\x0epeer_signature\x18\x02 \x01(\t\x12$\n\tpeer_info\x18\x03 \x01(\x0b\x32\x11.ClientAttributes\"n\n\x1bPeerVerificationTransaction\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12 \n\x18total_peer_request_count\x18\x04 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[protobuf_dot_digital__id__pb2.DESCRIPTOR,protobuf_dot_client__pb2.DESCRIPTOR,])




_PEERVERIFICATIONREQUEST = _descriptor.Descriptor(
  name='PeerVerificationRequest',
  full_name='PeerVerificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='digital_id', full_name='PeerVerificationRequest.digital_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_signature', full_name='PeerVerificationRequest.owner_signature', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remark', full_name='PeerVerificationRequest.remark', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peer_address', full_name='PeerVerificationRequest.peer_address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_timestamp', full_name='PeerVerificationRequest.create_timestamp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=221,
)


_PEERVERIFICATIONRESPONSE = _descriptor.Descriptor(
  name='PeerVerificationResponse',
  full_name='PeerVerificationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='digital_id', full_name='PeerVerificationResponse.digital_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peer_signature', full_name='PeerVerificationResponse.peer_signature', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peer_info', full_name='PeerVerificationResponse.peer_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=331,
)


_PEERVERIFICATIONTRANSACTION = _descriptor.Descriptor(
  name='PeerVerificationTransaction',
  full_name='PeerVerificationTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='PeerVerificationTransaction.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='PeerVerificationTransaction.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='PeerVerificationTransaction.type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_peer_request_count', full_name='PeerVerificationTransaction.total_peer_request_count', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=443,
)

_PEERVERIFICATIONRESPONSE.fields_by_name['peer_info'].message_type = protobuf_dot_client__pb2._CLIENTATTRIBUTES
DESCRIPTOR.message_types_by_name['PeerVerificationRequest'] = _PEERVERIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['PeerVerificationResponse'] = _PEERVERIFICATIONRESPONSE
DESCRIPTOR.message_types_by_name['PeerVerificationTransaction'] = _PEERVERIFICATIONTRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PeerVerificationRequest = _reflection.GeneratedProtocolMessageType('PeerVerificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _PEERVERIFICATIONREQUEST,
  '__module__' : 'protobuf.peer_verification_pb2'
  # @@protoc_insertion_point(class_scope:PeerVerificationRequest)
  })
_sym_db.RegisterMessage(PeerVerificationRequest)

PeerVerificationResponse = _reflection.GeneratedProtocolMessageType('PeerVerificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _PEERVERIFICATIONRESPONSE,
  '__module__' : 'protobuf.peer_verification_pb2'
  # @@protoc_insertion_point(class_scope:PeerVerificationResponse)
  })
_sym_db.RegisterMessage(PeerVerificationResponse)

PeerVerificationTransaction = _reflection.GeneratedProtocolMessageType('PeerVerificationTransaction', (_message.Message,), {
  'DESCRIPTOR' : _PEERVERIFICATIONTRANSACTION,
  '__module__' : 'protobuf.peer_verification_pb2'
  # @@protoc_insertion_point(class_scope:PeerVerificationTransaction)
  })
_sym_db.RegisterMessage(PeerVerificationTransaction)


# @@protoc_insertion_point(module_scope)
