# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/shared_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protobuf import digital_id_pb2 as protobuf_dot_digital__id__pb2
try:
  protobuf_dot_id__attribute__pb2 = protobuf_dot_digital__id__pb2.protobuf_dot_id__attribute__pb2
except AttributeError:
  protobuf_dot_id__attribute__pb2 = protobuf_dot_digital__id__pb2.protobuf.id_attribute_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/shared_id.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18protobuf/shared_id.proto\x1a\x19protobuf/digital_id.proto\"5\n\x12ShareIDTransaction\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\"\x85\x01\n\x0eShareIdRequest\x12 \n\x11ID_data_requested\x18\x01 \x01(\x0e\x32\x05.Bool\x12\x17\n\x0f\x63ontract_detail\x18\x02 \x01(\x0c\x12\x1a\n\x12\x63ontract_signature\x18\x04 \x01(\t\x12\x1c\n\x14recv_id_from_address\x18\x03 \x01(\t\"E\n\x0fShareIdResponse\x12\x19\n\x11\x64igital_signature\x18\x01 \x01(\t\x12\x17\n\x0fsend_to_address\x18\x02 \x01(\t\"g\n\x08\x63ontract\x12&\n\rattribute_set\x18\x01 \x01(\x0b\x32\x0f.IdAttributeSet\x12\x19\n\x11validity_in_years\x18\x02 \x01(\x05\x12\x18\n\x10\x63reate_timestamp\x18\x03 \x01(\t*\x1b\n\x04\x42ool\x12\t\n\x05\x46\x61lse\x10\x00\x12\x08\n\x04True\x10\x01\x62\x06proto3')
  ,
  dependencies=[protobuf_dot_digital__id__pb2.DESCRIPTOR,])

_BOOL = _descriptor.EnumDescriptor(
  name='Bool',
  full_name='Bool',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='False', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='True', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=422,
  serialized_end=449,
)
_sym_db.RegisterEnumDescriptor(_BOOL)

Bool = enum_type_wrapper.EnumTypeWrapper(_BOOL)
globals()['False'] = 0
globals()['True'] = 1



_SHAREIDTRANSACTION = _descriptor.Descriptor(
  name='ShareIDTransaction',
  full_name='ShareIDTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='ShareIDTransaction.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='ShareIDTransaction.action', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=108,
)


_SHAREIDREQUEST = _descriptor.Descriptor(
  name='ShareIdRequest',
  full_name='ShareIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID_data_requested', full_name='ShareIdRequest.ID_data_requested', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contract_detail', full_name='ShareIdRequest.contract_detail', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contract_signature', full_name='ShareIdRequest.contract_signature', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recv_id_from_address', full_name='ShareIdRequest.recv_id_from_address', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=244,
)


_SHAREIDRESPONSE = _descriptor.Descriptor(
  name='ShareIdResponse',
  full_name='ShareIdResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='digital_signature', full_name='ShareIdResponse.digital_signature', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='send_to_address', full_name='ShareIdResponse.send_to_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=315,
)


_CONTRACT = _descriptor.Descriptor(
  name='contract',
  full_name='contract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attribute_set', full_name='contract.attribute_set', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validity_in_years', full_name='contract.validity_in_years', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_timestamp', full_name='contract.create_timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=420,
)

_SHAREIDREQUEST.fields_by_name['ID_data_requested'].enum_type = _BOOL
_CONTRACT.fields_by_name['attribute_set'].message_type = protobuf_dot_digital__id__pb2._IDATTRIBUTESET
DESCRIPTOR.message_types_by_name['ShareIDTransaction'] = _SHAREIDTRANSACTION
DESCRIPTOR.message_types_by_name['ShareIdRequest'] = _SHAREIDREQUEST
DESCRIPTOR.message_types_by_name['ShareIdResponse'] = _SHAREIDRESPONSE
DESCRIPTOR.message_types_by_name['contract'] = _CONTRACT
DESCRIPTOR.enum_types_by_name['Bool'] = _BOOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShareIDTransaction = _reflection.GeneratedProtocolMessageType('ShareIDTransaction', (_message.Message,), {
  'DESCRIPTOR' : _SHAREIDTRANSACTION,
  '__module__' : 'protobuf.shared_id_pb2'
  # @@protoc_insertion_point(class_scope:ShareIDTransaction)
  })
_sym_db.RegisterMessage(ShareIDTransaction)

ShareIdRequest = _reflection.GeneratedProtocolMessageType('ShareIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHAREIDREQUEST,
  '__module__' : 'protobuf.shared_id_pb2'
  # @@protoc_insertion_point(class_scope:ShareIdRequest)
  })
_sym_db.RegisterMessage(ShareIdRequest)

ShareIdResponse = _reflection.GeneratedProtocolMessageType('ShareIdResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHAREIDRESPONSE,
  '__module__' : 'protobuf.shared_id_pb2'
  # @@protoc_insertion_point(class_scope:ShareIdResponse)
  })
_sym_db.RegisterMessage(ShareIdResponse)

contract = _reflection.GeneratedProtocolMessageType('contract', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACT,
  '__module__' : 'protobuf.shared_id_pb2'
  # @@protoc_insertion_point(class_scope:contract)
  })
_sym_db.RegisterMessage(contract)


# @@protoc_insertion_point(module_scope)
